version: '3.3'
services:

  app:
    build: app
    volumes:
    - ./app:/app
    ports:
    - 5000:5000
    command: python app.py

  apm:
    build: .
    ports:
    - 8200:8200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
